### ISSUE TITLE
Persistence existingClaimName doesn't work

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/helm-charts#110]
Using :

```yaml
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    persistentVolumeClaim:
      existingClaimName: existing-claim-name
```

A claim is created:
```yaml
# Source: headscale/templates/replicated-library.tpl
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: net1-data
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: headscale
    app.kubernetes.io/version: "1"
    helm.sh/chart: headscale-0.0.1
  annotations:
```

According to the comments the existingClaimName should override the creation of the PVC. Baring a typo it doesn't appear that existingClaims are working in persistence.

**Comment by diamonwiggins** [comment]
@chris-sanders I'm thinking this might be a holdout from how we were thinking about storage in the early days. With the current API, i'm not sure how much a `existingClaimName` would make sense. I think it may have made more sense before when details of how the volume would be mounted were in the persistence properties, but that's no longer the case. `volumeMounts` are specified directly on the container in the app as is the `claimName` for a PVC. So i'm not sure what a persistent object with a `existingClaimName` in our library would do.

**Comment by chris-sanders** [comment]
@diamonwiggins let me think that through. So if I write a chart and I need storage mounted into the pod. I specify some storage under `persistence` and mount the volume and volume mount on the pod. I know the name of the persistence.

Then a user wants to use my chart but has an existing claim. It seems reasonable they could just add:
```
persistence:
  data:
    existingClaim: my-existing-claim
```

And then the data volume that the chart uses would use that claim everywhere the `data` persistence object was being used.

Are you suggesting instead that the user just modify the volume directly on the container? While I suppose that could work, the UX of a user having to instead specify:
```
app:
  my-app:
    volumes:
      - data-volume:
        persistentVolumeClaim:
          claimName: my-existing-claim
      - duplicated w/o changing all other volumes on this pod
```
Which I think requires them to look up all existing volumes and manually provide those as well (b/c it's a list). It's also a pretty unintuitive way to use an existing claim vs the 3 lines above.

What am I missing, have I mapped something out wrong here?

**Comment by chris-sanders** [comment]
The part I think you're missing is this: `Then a user wants to use my chart`

It's not for the chart author, I'm talking about the person that consumes the chart. The `existingClaim` is not for the chart author that's a field for an end user consuming the chart. That's why I'm not talking about `volumeMounts` those don't need to change, all that the _end user_ needs to change is what the PVC name is the mounting portion doesn't change.

**Comment by diamonwiggins** [comment]
This discussion has me thinking that sometimes it's a gray area who we're developing certain abstractions in the chart for. The person using the library to build and distribute their chart, or the ultimate end user? For the former, some abstractions may not make sense, whereas for the ultimate end user, if they ever need to modify the values.yaml before installing, they may rather see a flatter config file instead of one that looks more like a kubernetes manifest. For that end-user persona I understand you're concern about a user needing to go and modify the volume/volumeMounts on the Pod directly, but it is pretty consistent with how a compose file looks, so i don't consider it THAT complicated https://docs.docker.com/compose/compose-file/07-volumes/#example. 

Good topic of discussion though.

**Comment by diamonwiggins** [comment]
Yeah, per my last comment I understand what you're saying. We'll need to think through the design on this though if it's something we want to add. It almost feels like it could be in the territory of something you'd expect chart developers to template themselves. With our current design it'd be confusing to me seeing the following in the `values.yaml` I was given as an end-user:

```yaml
    containers:
      vaultwarden:
        image:
          repository: vaultwarden/server
          tag: 1.27.0-alpine
        volumeMounts:
        - mountPath: /data
          name: vaultwarden
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: vaultwarden
    volumes:
    - name: vaultwarden
      persistentVolumeClaim:
        claimName: vaultwarden
```

but also:

```yaml
persistence:
  vaultwarden:
    existingClaim: my-existing-claim
```

As a chart developer I wouldn't want to distribute a values.yaml that had the `claimName` set in two difference places even if the one in the `persistence` area was going to override it somehow?

**Comment by chris-sanders** [comment]
Well I don't think you would see that. What you would see is:

```
persistence:
  vaultwarden:
    # Existing claims will take priority over this spec if specified
    # existingClaim: my-existing-claim
    sepc:
       ... <- the spec here
```
The point being the chart author can never specifiy an existing claim, it's only ever usable as an end user providing an override. Also what I'm showing above is already in the library chart, it already says it will work this way in the comments.

Then if a chart author wants to make it even more clear, you can use advanced templating to provide a 'flatter' configvalue which you map into this field. Although, being only 3 enteries deep I personally wouldn't bother. Although we might just talk in real time this afternoon to make this easier :)

I ask b/c I'm trying to do this right now: https://github.com/chris-sanders/helm-charts/blob/master/charts/headscale/values.yaml

And it's preventing me from finishing the chart. So I'm likely to work on it this weekend if we figure out what it _should_ do.

**Comment by chris-sanders** [comment]
Here's a specific example. I don't think it's old functionality I think it's necessary for claims to work correctly.

```
apps:
  headscale:
    enabled: true
    type: statefulset
    containers:
      headscale:
        command:
          - headscale
        args: 
          - serve
        ports:
        - name: http
          containerPort: 8080
        - name: grpc
          containerPort: 50443
        - name: derp
          containerPort: 3478
        volumeMounts:
        - name: data
          mountPath: /vol/data
        - name: config
          mountPath: /etc/headscale/config.yaml
          subPath: etc
          readOnly: true
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
    - name: config
      configMap:
        name: net1-headscale

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    persistentVolumeClaim:
      #existingClaimName: existing-claim-name
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        persistentvolumeReclaimPolicy: Retain
        resources:
          requests:
            storage: 1Gi
```

In this file the data persistent volume is mounted into the pod and is the default configuration for the chart. However, a user needs to be able to re-use an existing claim. If they specify the `existingClaimName` field on the data persistence object what should happen is the chart should use _that_ rather than calculating a name with prefix for the _data_ persistence.

The only alternative here is that the end user has to re-write the `volumes` section as currently implemented and change the claim name. Which is what I show above. We already calculate (incorrectly) the prefix here, that needs to be fixed but it also needs to properly check the existing claim name as well.

**Comment by chris-sanders** [comment]
here's a valid values.yaml with the chart taking care of existing claims.
```
persistence:
  data:
    persistentVolumeClaim:
      existingClaimName: my-awesome-claim
```

Here it is w/o it today
```
apps:
  headscale:
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-awesome-claim
    - name: config
      configMap:
        name: net1-headscale

persistence:
  data:
    enabled: false
```

It is possible, but it's not straight forward. And every chart would have to document this process, where as a single comment in the values file indicates how it works if implemented as the library says it is today.
