### ISSUE TITLE
livenessProbe type `exec` renders incorrectly

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/helm-charts#121]
with values.yaml

```
apps:
  app1:
    containers:
      base:
        image:
          repository: hello-world
          tag: '1'
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pidof node
```

renders

```
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - pidof node
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            terminationGracePeriodSeconds: 30
            timeoutSeconds: 5
```

the additional `httpGet:` stanza causes the manifest to fail validation
