### ISSUE TITLE
Pattern for hashing pod envFrom target to automatically roll deployments

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/helm-charts#124]
yeah hi hello :wave: 🙂  - first time trying this project for a real use case, and gotta say it's pretty nifty 🙂  the vaultwarden example in replicated-starter-helm was very helpful

I didn't look very closely, but I'm wondering if there's a way to opt-in to some kind of configmap/secret checksumming to automatically roll deployments 

Example in helm docs: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

```
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
[...]
```

here's a redacted version of my YAML

```
apps:
  metalytics-worker:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      worker:
        image:
          repository: metalytics-worker
          tag: latest
        envFrom:
          - secretRef:
              name: metalytics

  metalytics-api:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      api:
        image:
          repository: metalytics-api
          tag: latest
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: metalytics

services:
  metalytics-api:
    enabled: true
    appName: ["metalytics-api"]
    type: NodePort
    ports:
      http:
        enabled: true
        port: 8080
        protocol: HTTP
        targetPort: 8080
        nodePort: 8080

secrets:
  metalytics:
    enabled: true
    data:
      LOG_LEVEL: "debug"
      API_URL: "http://metalytics-api:8080"
      # ... etc
```
