### ISSUE TITLE
VolumeClaimTemplates naming is not intuitive

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/helm-charts#127]
I read [the example](https://github.com/replicatedhq/helm-charts/blob/main/charts/replicated-library/values-example.yaml#L180C1-L181C29)

```
    # -- Used to create individual disks for each instance when type: StatefulSet
    volumeClaimTemplates: []
```
and assumed we do a standard volume claim template, as in the k8s docs, stackoverflow, GPTs, etc

```
    volumeClaimTemplates:
      - metadata:
           name: redis-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: ebs-sc
```

This results in 
```
  volumeClaimTemplates:
  - metadata:
      name:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: ebs-sc
```

Which causes an error when provisioning since `-redis-0` is not a valid PVC name.

It turns out the correct invocation is

```diff
    volumeClaimTemplates:
-     - metadata:
-          name: redis-data
+     - name: redis-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: ebs-sc
```

### proposal

at the very least, probably link to to where this is used so folks can check the correct usage

```diff
    # -- Used to create individual disks for each instance when type: StatefulSet
+    # [[ref]](https://github.com/replicatedhq/helm-charts/blob/07d413840502b203fe6299e69a363d019dc83f6c/charts/replicated-library/templates/lib/_statefulset.tpl#L86)
    volumeClaimTemplates: []
```
