### ISSUE TITLE
[Library] Default probe values

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/helm-charts#23]
Currently while a user can define the liveness, readiness, and startup probes you have to basically write it your self directly. I wonder if we could make a reasonable set of defaults which you can override/set via config variables. We could still leave a sub-command like "custom" that let's you drop in raw yaml.

Most of the time would be perfectly happy with an initial probes with an initial set of timeouts that aren't terribly aggressive. Then I could always adjust the port or tighten up the timing if I felt so inclined. Generally speaking though it's good practice to have and I think we can make reasonable assumptions so users don't need to do anything or only need to make a small tweak.

**Comment by chris-sanders** [comment]
Just as a starting point here's an example. If we were to pick the first port on a conatiner and just use tcp socket checks.

```
livenessProbe:
  tcpSocket:
    port: 51821
  initialDelaySeconds: 15
  failureThreshold: 5
  timeoutSeconds: 5
  periodSeconds: 20
readinessProbe:
  tcpSocket:
    port: 51821
  initialDelaySeconds: 10
  failureThreshold: 5
  timeoutSeconds: 5
  periodSeconds: 10
startupProbe:
  tcpSocket:
    port: 51821
  initialDelaySeconds: 10
  failureThreshold: 5
  timeoutSeconds: 5
  periodSeconds: 10
```

We could tweak any of these but there's a lot of duplication here that I suspect we could at least make easier but most of the just checking that the port is working is better than nothing at all.

**Comment by diamonwiggins** [comment]
@chris-sanders I had taken a first pass at this in https://github.com/replicatedhq/helm-charts/pull/16 which should be available in `v0.3.0`. However, it doesn't _always_ set the defaults. It only does so if you configuring _something_ in the probes yourself, so:

user-values.yaml
```
probes:
  readinessProbe:
    tcpSocket:
      port: 51821
```

Would be merged in with the defaults specified [here](https://github.com/replicatedhq/helm-charts/blob/main/charts/replicated-library/values.yaml#L7)

However if you have:

```
probes:
  readinessProbe: {}
```

Then we won't do anything because for any of the probe config like timeoutSeconds, etc can be useful you need the user to configure `exec`, `http`, `tcpSocket`, etc.

Now if you're suggesting we always try to find a way to set a default probe for everyone, I feel like that could be a little challenging as `readiness/liveness/startup` can be very subject and specific to the app. The question to answer is, "Does simply taking a port specified on the container give you enough information to know you can set a probe for that?" Maybe in 90% of use cases it does, but for someone it might be unexpected.

**Comment by chris-sanders** [comment]
Oh great I'll check that out, that's why I was just suggesting tcpSocket. All that checks is that a connection can be established, which if you have a port defined should always be a safe check I think?

I'm curious is there a reason the probes are:
```
containers:
  my-container:
    probes:
      readinessProbe: {}
```

Instead of:
```
containers:
  my-container:
    readinessProbe: {}
```

The sub-key of `probes` is not actually in the spec. Where as `ports` for example is, seems like the probes should just be defined directly on the container just like the actual spec? I was expecting to find them on the same level as `ports`, `env`, `envFrom`, and `securityContext`.
