### ISSUE TITLE
Helm charts will not install when configMaps are enabled in 0.6.0 - 0.5.0-3 versions

### ISSUE THREAD

**Issue by drohnow** [replicatedhq/helm-charts#48]
Charts will not install on versions greater than 0.4.0 when configMaps are enabled.

The following error is output:
Error: INSTALLATION FAILED: Deployment.apps "mine-minecraft-minecraft" is invalid: spec.template.spec.containers:
Required value

Helm chart will render for all versions tested (0.6.0, 0.5.0-3, 0.4.0) but the chart will only install with version 0.4.0.
```
#helm template ./chart
apiVersion: v1
            kind: ConfigMap
            metadata:
              name: release-name-minecraft-minecraft
              labels:
                app.kubernetes.io/instance: release-name
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/name: minecraft
                app.kubernetes.io/version: 1.16.0
                helm.sh/chart: minecraft-0.1.0
            data:
              foo: bar
```

Chart installed with 0.4.0 version:

```
 helm install mine ./minecraft/
                NAME: mine
                LAST DEPLOYED: Thu Apr 20 01:14:03 2023
                NAMESPACE: minecraft
                STATUS: deployed
                REVISION: 1
                TEST SUITE: None

            # kubectl get cm
                minecraft          1      24s

```
values.yaml:

```
global:
              labels: {}
              annotations: {}
            
            
            apps:
              minecraft:
                enabled: true
                type: deployment
                replicas: 1
                containers:
                  minecraft:
                    image:
                      repository: itzg/minecraft-server
                      tag: latest
                    volumeMounts:
                      - mountPath: /data
                        name: minecraft
                    env:
                     EULA: "TRUE"
                     GAMEMODE: survival
                     DIFFICULTY: normal
                     WHITE_LIST: "true"
                     ONLINE_MODE: "true"
                    ALLOW_CHEATS: "true"
                volumes:
                  - name: minecraft
                    persistentVolumeClaim:
                      claimName: minecraft-pvc
                fullNameOverride:
            
            configmaps:
              minecraft:
                # -- Enables or disables the configMap
                enabled: true
                # -- Labels to add to the configMap
                labels: {}
                # -- Annotations to add to the configMap
                annotations: {}
                # -- configMap data content. Helm template enabled.
                data:
                  foo: bar
                  # foo: bar
                # -- Override the name of this object. Default name if not overwritten will be releaseName-ChartName-objectName
                fullNameOverride:
            
            
            
            secrets:
              minecraft:
                # -- Enables or disables the se
                enabled: true
                # -- Labels to add to the secre
                labels: 
                  location: SanDiego 
                # -- Annotations to add to the 
                annotations: {}
                # -- configMap data content. He
                data:
                    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1akNDQXFLZ0F3SUJBZ0lVUllJQ2FUb0o1R1laQ0tiSjdMazh0UTJyZHVRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FERWRNQnNHQTFVRUF3d1ViV2x1WldOeVlXWjBMbkp2YUc1dmR5NXVaWFF4Q3pBSkJnTlZCQVlUQWxWVApNUkl3RUFZRFZRUUhEQWxUWVc0Z1JHbGxaMjh3SGhjTk1qTXdOREU1TURRd05qRXdXaGNOTWpRd05ERTRNRFF3Ck5qRXdXakJ4TVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVTTUJBR0ExVUUKQnd3SlUyRnVJRVJwWldkdk1ROHdEUVlEVlFRS0RBWlNiMmh1YjNjeEV6QVJCZ05WQkFzTUNsSnZhRzV2ZHlCRQpaWFl4RXpBUkJnTlZCQU1NQ25KdmFHNXZkeTV1WlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEU2w4eFhXMmRLd2t5UmZTa2RqT2xoY3VzM2FOeDYrRDJDUi9hbG0zbG1UNGtkQVc4VFd3cUcKc0M3c0dSQS9IZzVSanpWVzdsVHN0Z1NlbmY2N0hpTFFjZTJBOUwvemNpVXJLUHUvWjZLT0dQdlNOOXR0SFNNTgozWGkrZEFwM01RVEMxZk5xazgwRldMcTIzdXpyR2VBaXArbkwwbEdiakJRZjV0OUVJNXFrVC8wZXRYYXlkNkpFCnI2RUI0ZHRtN1lxYi80K3FFQytEV0d5bElreEZMeTlmT1Y3T2k0SDQ4V3k2U0JMdlN0TWhIRnRSb2tpbDVBMlYKK044T1pOUW1qaGE2Y0Q4RFFXNlVwK1VKYVh2QU1UQXZEZWxxY3ZKM21kS0FIdjJITTF4ZUludFdKMEtiL0t0bApRU0lkNWYrMlFienNCN1FObGZNMHZpRGU1ZDdacVNPOUFnTUJBQUdqZXpCNU1COEdBMVVkSXdRWU1CYUFGTm5NCmZUUnNySTl1cVMvdG1GNXBBa1liYUY3Tk1Ba0dBMVVkRXdRQ01BQXdDd1lEVlIwUEJBUURBZ1R3TUI4R0ExVWQKRVFRWU1CYUNGRzFwYm1WamNtRm1kQzV5YjJodWIzY3VibVYwTUIwR0ExVWREZ1FXQkJRZjNIc2RXU1ZZNHZORApOWE40OEFFbC9ZSm5yVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUnlwT3BkbWY1OHRTZTdHMXAvcWtpZmpkCnRXN3RUbGdldzV2M1JvbTVTbk1XanpCVFNHeE4xbmNNNGhqUGdjTnI0QUgwSDl2RktyRlF6dS9vdzAwUWZwK1QKU0d5bVBreFVIK2Q0eGtBOFpKNldRbWQ1SjA0SE56Tm5DMDNXSW1NRktBQUk4emxrN2JGWkdMN0VIYzVhRUYydQpmeElwdTRrZEJwZmhTeGExSXV2aVRTU050RUxIaTBJUXlvcC9yaEc3QjgwdjE2L1VMN000NUt6RU9FeVh3TEdFClZTMmxEeFF4TEYwV0ZFN1JFem5HbStsYW1DRzlrSlkwZjVwaXFpSTdNU2lDNVdyM1kyTlFERWdqbkpYanNYcVQKQi9vL01nWmh5cjA1YzdwbkovS0wwaTRzaTRabStzNXJGWnJnaUV0V3duUlVZWmE0TWRTbXlrdTdSaXd6UWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
                    tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFNsOHhYVzJkS3dreVIKZlNrZGpPbGhjdXMzYU54NitEMkNSL2FsbTNsbVQ0a2RBVzhUV3dxR3NDN3NHUkEvSGc1Ump6Vlc3bFRzdGdTZQpuZjY3SGlMUWNlMkE5TC96Y2lVcktQdS9aNktPR1B2U045dHRIU01OM1hpK2RBcDNNUVRDMWZOcWs4MEZXTHEyCjN1enJHZUFpcCtuTDBsR2JqQlFmNXQ5RUk1cWtULzBldFhheWQ2SkVyNkVCNGR0bTdZcWIvNCtxRUMrRFdHeWwKSWt4Rkx5OWZPVjdPaTRINDhXeTZTQkx2U3RNaEhGdFJva2lsNUEyVitOOE9aTlFtamhhNmNEOERRVzZVcCtVSgphWHZBTVRBdkRlbHFjdkozbWRLQUh2MkhNMXhlSW50V0owS2IvS3RsUVNJZDVmKzJRYnpzQjdRTmxmTTB2aURlCjVkN1pxU085QWdNQkFBRUNnZ0VBQ2RJcGNyTjZvcGN3RlNMY25ZQjZTOGNEczF1RVB5QS9pSHlNM0pZUjNwU3YKS3lxZXB2bTZiejFkSjZBai83aTlOTTVPQXYrNmtNSS81Um91OHQyV25qOVdzdGNxV04vRjk4VTAwU0JuQ1piUgpyc3FMRVoxT0pFdDlTRlZHMTBTL1A1Z0lHRlgvTmNlNG9XWm5ieFlwSWdTYzErYzNINnZObE51dkpnUnhERWE5ClpZVUdvTlg5Y0U1SjZhYzE5Y05xUGNYclVHK2dOZW85aVp3RTY4L1dKVFY1UWlwQ3hYbHpXeUE0akNoWjdNRS8KS2FidXg2eXY5M2NTOGRSeG5temI5OWxLVVNjRjMyemltUmZDQmZyNnQvL01TbG9XWVZ1MG8zUnhBT0xsRGV4YgovNURpdTZsdlJVcjNROHBpa0ovL2t1S3ZEVnV0UjhuMS9GdTZsSmMrQXdLQmdRRDB3QjFleGxkY2FvdXNqdnlhCmN5NHo0OUR4Um5kNGl2WU5uR1NtY1FxT1k2T3RlRnBDRURHRnJtMjk5T2R6bW4yZjNsNGVCeW5wSFYrSzZzSXoKMzZ0bjhVeDN2KzBRdFBTS2dBTWFmcVZuSldqdHFERDJ4VkVRODdlZWxFS0xPS0FlZzdnNmlxN25mVlRZSlJrOQorT2FDVUk1SEdyelFHZ2xPTEpGN0JiQXpxd0tCZ1FEY1JjUHVIc2lQWHE2bFBaSXZ1WDVTbitDNjQzQXY0b0tICi9VTEFIbWpVdWd4WDcxVHR6OGx3dm1BZ1U5UW1wcjZ6MWlGWUhEaWdpdDlOV0lnVCtJTUMwcVp3enl5Y2hmaDAKY2lzUENGcUFDcGtTekNLVURmcWZxWElQOWF2bENkRUpzZStGaDZMZlhGSzdrcCtjOVk0U2ZLbDhGdFJrbTgzcApaUE1iTUVBZU53S0JnUURGdklEK0ZSaDNuYzBDdVBMMGhhSUtZa0JvN2htUDFoVThvZUhmWnV5MFpXUFR2cXlOCk96QUhaUWxjc3dSYnJiRlkrL3JtSDd1SWp5YWx3VXp0UkFQamtsdkpVOUpmOFJLdzR3T2U0RHNadm11cnRucjQKcENuK25DajVnYWJSZkFwQkhRSTJxZHp0UWFET2tBcDR1eUxnbmR5VkxkRG1BR01NT1kyLzZyU1V5UUtCZ1FDeQpPckVDWjE0WXc1L0VqRUZRNUdKV01JOENLUzJKVVZvVTl0T2Y1L3NpeFRkZm40TzB1TUJodldqQ1A1SVZoQzRpCkRVMEZvakFmbHI2QU12WklVbmlQUENyNGRHbkFiSlpRZ21CYzFZR0V3UTZDcXpIL1lpQThPRHJXdHczVFVWSVcKNmliSWdLdEUxOHNKZ3VZcmRuVHllSFFhdDg0N2FlWCt4M1A5dDlqcG1RS0JnSDh4R3FkcXFBbFBkZlRVcitRUApLdmJkMnlzdXFTbmdpbEpvT0o3dXdqeUg5WlYrQ1VkcDB4RkRBTzc0OE5GcHdJSTd6ZmVuWlIyKzM1U1Y4MWZyCkpOYlRYRTRNUzlZbG5YR0NPTndFUjJxREJFRTU1Wk5kSW5ZV0xabzE2YjM4VC95RXd4d1RuTHVHeEt4clZuRmwKbFAzYnFvR0sxZkhUNlcyTzJMWmdJSyt1Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
                  # foo: bar
                # -- Override the name of this 
                fullNameOverride: minecraft-tls
                type: kubernetes.io/tls
               
            
            services:
              minecraft-svc:
                enabled: true
                appName: minecraft
                type: ClusterIP    
                ports:
                  minecraft:
                    enabled: true
                    port: 25565
                    protocol: TCP
                    targetPort: 25565
                fullNameOverride: minecraft-svc
                    
            ingresses:
              minecraft:
                enabled: true
                serviceName: minecraft-svc
                annotations: 
                  #ingress.kubernetes.io/force-ssl-redirect: "true"
                hosts:
                  - host: minecraft.rohnow.net
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          port: 25565
                #tls: 
                #- secretName: minecraft-tls
                          
            persistence:
              minecraft:
                enabled: true
                fullNameOverride: minecraft-pvc
                type: persistentVolumeClaim
                persistentVolumeClaim:
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 50Gi

```

**Comment by drohnow** [comment]
@chris-sanders I have a configmap enabled in my values file (see attached) and I receive the following errors with the version / branch specified:

Version 0.7.0 error:
Error: INSTALLATION FAILED: Deployment.apps "mongodb" is invalid: [spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"garage", "app.kubernetes.io/name":"dagr"}: `selector` does not match template `labels`, spec.template.spec.containers: Required value]

Version 0.7.0 + csanders/configmap-name-override branch error:
Error: INSTALLATION FAILED: Deployment.apps "garage-garagersvp-webui" is invalid: spec.template.spec.containers: Required value
note: same error as we get with 0.6.0 - 0.5.0-3 versions.

[values.txt](https://github.com/replicatedhq/helm-charts/files/11299916/values.txt)

**Comment by drohnow** [comment]
@chris-sanders  I still think this is an issue here; tested with 0.7.1.

I went ahead and used the default values.yaml file to ensure that custom values or end user error were not the issue.

Test 1:
- values.yaml: The changes (see values copy.yaml--app-enabled.txt)
      `apps:
           webui:
               enabled: true
          containers:
            webui:`

- helm template ./chart
   manifests rendered (notice the containers section; it looks good):
   
   `---
# Source: garagersvp/templates/replicated-library.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-garagersvp-webui
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garagersvp
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: garagersvp-0.1.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: webui
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webui
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: 
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: webui
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
`

- helm install test ./chart
   results: chart deploys successfully

Test 2:
- values.yaml: The changes (see values copy.yaml--app-enabled-configmap-enable.txt)
      `apps:
           webui:
               enabled: true
          containers:
            webui:

       configmaps:
          webui-cm:
              enabled: true
              data:
                   foo: bar
`

- helm template ./chart
   manifests rendered (notice the containers section; does not look good; empty):
   
   `
    ---
# Source: garagersvp/templates/replicated-library.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-garagersvp
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garagersvp
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: garagersvp-0.1.0
data:
  foo: bar
---
# Source: garagersvp/templates/replicated-library.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-garagersvp-webui
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garagersvp
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: garagersvp-0.1.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: webui
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        
        checksum/config: d4c7c16e42c9515d75bdbf72382673ecb7742e949c00b98b5d552628e5d5b226
      labels:
        app.kubernetes.io/name: webui
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: 
      automountServiceAccountToken: 
      dnsPolicy: ClusterFirst
      enableServiceLinks: 
      containers:
`

- helm install test ./chart
   results: chart will not deploy
   error: Error: INSTALLATION FAILED: Deployment.apps "test-garagersvp-webui" is invalid: spec.template.spec.containers: Required value


[values copy.yaml--app-enabled.txt](https://github.com/replicatedhq/helm-charts/files/11313574/values.copy.yaml--app-enabled.txt)

[values copy.yaml--app-enabled-configmap-enable.txt](https://github.com/replicatedhq/helm-charts/files/11313577/values.copy.yaml--app-enabled-configmap-enable.txt)

**Comment by chris-sanders** [comment]
I'll reopen this until we see if the new failure is related.

**Comment by chris-sanders** [comment]
@drohnow can you correct the formatting on this? Yaml w/o code formatting is hard to understand.

I'd like to see for the failing case.
* The input
* What the output that it generates is
* The error message the install generates (I think I have this)

**Comment by drohnow** [comment]
@chris-sanders  Here you go.

Test 1:

```
apps:
  webui:
    enabled: true
    containers:
      webui:
```

- helm template ./chart
   manifests rendered (notice the containers section; it looks good):

```
 helm template ./test/
---
# Source: test/templates/replicated-library.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-test-webui
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: test-0.1.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: webui
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webui
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: 
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: webui
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent

```
- helm install test ./chart
   results: chart deploys successfully

Test 2:
- values.yaml: The changes (see values copy.yaml--app-enabled-configmap-enable.txt)
 
```
apps:
  webui:
    enabled: true
    containers:
      webui:

configmaps:
  webui-cm:
    enabled: true
    data:
      foo: bar
```

- helm template ./chart
   manifests rendered (notice the containers section; does not look good; empty):

```
helm template ./test/
---
# Source: test/templates/replicated-library.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-test-webui-cm
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: test-0.1.0
data:
  foo: bar
---
# Source: test/templates/replicated-library.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-test-webui
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: test-0.1.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: webui
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        
        checksum/config: afb6ad13f2232067254e6d57084c3ba86122c1ab16eb9a5342f2ce715100d027
      labels:
        app.kubernetes.io/name: webui-cm
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: 
      automountServiceAccountToken: 
      dnsPolicy: ClusterFirst
      enableServiceLinks: 
      containers:

```

- helm install test ./chart
   results: chart will not deploy
   error: Error: INSTALLATION FAILED: Deployment.apps "test-garagersvp-webui" is invalid: spec.template.spec.containers: Required value

```
helm install test ./test/
Error: INSTALLATION FAILED: Deployment.apps "test-webui" is invalid: [spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"test", "app.kubernetes.io/name":"webui-cm"}: `selector` does not match template `labels`, spec.template.spec.containers: Required value]

```


[values copy.yaml--app-enabled.txt](https://github.com/replicatedhq/helm-charts/files/11313574/values.copy.yaml--app-enabled.txt)

[values copy.yaml--app-enabled-configmap-enable.txt](https://github.com/replicatedhq/helm-charts/files/11313577/values.copy.yaml--app-enabled-configmap-enable.txt)
