### ISSUE TITLE
volumeClaimTemplates in libs/_statefulset.tpl fix metadata.name rendering

### ISSUE THREAD

**Issue by drohnow** [replicatedhq/helm-charts#55]
libs/_statefulset.tpl:

Current Config:
```
 {{- if $values.volumeClaimTemplates }}
 volumeClaimTemplates:
 {{- range $name, $vct := $values.volumeClaimTemp
 - metadata:
     name: {{ $name }}
   spec:
     {{- toYaml $vct.spec | nindent 6 }}
 {{- end }}
 {{- end }}
{- end }}
```

when run: helm template ./chart
output: 

```
 volumeClaimTemplates:
  - metadata:
      name: 0
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: default
      volumeMode: Filesystem
```
notice metadata.name is 0

when attempt to install chart (helm install test ./chart):
results: failed
error: Error: INSTALLATION FAILED: StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal number into Go struct field ObjectMeta.spec.volumeClaimTemplates.metadata.name of type string

I have a PR that will be ready in a few minutes to solve:

```
  {{- if $values.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- range $index, $vct := $values.volumeClaimTemplates }}
  - metadata:
      name: {{ $vct.name }}
    spec:
      {{- toYaml $vct.spec | nindent 6 }}
  {{- end }}
  {{- end }}
{{- end }}

```
