### ISSUE TITLE
Custom serviceName in values.yaml is not being rendered in templates -- headless service

### ISSUE THREAD

**Issue by drohnow** [replicatedhq/helm-charts#58]
I am not able to set the serviceName manually in the values.yaml file.  When I add a serviceName & clusterIP=None value in the values.yaml; templates still render the default value set in the _statefultset.tpl.

1. set serviceName and set clusterIP=None in values.yaml
 ```
apps:
  mongodb:
    enabled: true
    type: statefulset 
    fullNameOverride:
    serviceName: mongodb

services:
 mongodb:
    enabled: true
    appName:
    fullNameOverride: mongodb
    type: ClusterIP
    clusterIP: None
```

2. helm template ./chart | grep serviceName

```
 serviceName: release-name-garagersvp-webui
```
Results:
- Chart will deploy but my expectation is that the servcieName defined in the statefulset manifest should be set to "mongodb".
- kubectl get po <mongodb-pod-name> -o yaml | grep subdomain
   output:  subdomain: garage-garagersvp-mongodb
- exec into dnsutils pod --> nslookup mongodb.garage --> host x.x.x.x
   output: name pointer 10-32-2-178.mongodb.garage.svc.cluster.local. (note: does not look correct)

Expected:
- kubectl get po <mongodb-pod-name> -o yaml | grep grep webui
   output: subdomain: mongodb
- exec into dnsutils pod --> nslookup mongodb.garage --> host x.x.x.x
   output: name pointer garage-garagersvp-mongodb-2.mongodb.garage.svc.cluster.local (looks correct).

values.yaml:
[values.yaml.txt](https://github.com/replicatedhq/helm-charts/files/11325950/values.yaml.txt)
