### ISSUE TITLE
Excess whitespace in pod spec

### ISSUE THREAD

**Issue by danj-replicated** [replicatedhq/helm-charts#91]
In a simple setup with no image pull secrets, excess white space is created in the pod spec.

```
# Source: helm-test/templates/replicated-library.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-helm-test-vaultwarden
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helm-test
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: helm-test-0.1.0
spec:
  revisionHistoryLimit: 
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: release-name
  serviceName: release-name-helm-test-vaultwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: release-name
    spec:
      
      serviceAccountName: 
      automountServiceAccountToken: 
      dnsPolicy: ClusterFirst
      enableServiceLinks: 
```
