### ISSUE TITLE
Invalid support bundle spec rendered from wg-easy chart

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/helm-charts#98]
Using the version `0.13.3` of the `replicated-library` dependency, the support bundle rendered from `wg-easy` chart looks like below. Note that the `selector` fields of the `exec` collectors are off

```yaml
---
# Source: wg-easy/templates/replicated-library.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-wg-easy-support-bundle-replicated
  labels:
    troubleshoot.io/kind: support-bundle
stringData:
  support-bundle-spec: |-
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: release-name-wg-easy-support-bundle-replicated
    spec:
      collectors:
        - clusterInfo: {}
        - clusterResources: {}
        - ceph: {}
        - longhorn: {}
        - exec:
            selector:
              name: weave-net
              - /home/weave/weave
            collectorName: weave-status
            name: kots/kurl/weave
            containerName: weave
            name: kots/kurl/weave
            namespace: kube-system
            timeout: 10s
            args:
              - --local
              - status
        - exec:
            selector:
              name: weave-net
              - /home/weave/weave
            collectorName: weave-report
            name: kots/kurl/weave
            containerName: weave
            name: kots/kurl/weave
            namespace: kube-system
            timeout: 10s
            args:
              - --local
              - report
```

Chart.lock file of `wg-easy` chart
```
dependencies:
- name: replicated-library
  repository: https://replicatedhq.github.io/helm-charts
  version: 0.13.3
digest: sha256:29a74f7d1fe860c12e76e3a959dee8b8a8c9ea44e84162910fcf964a723374a2
generated: "2023-06-02T13:40:09.475514+01:00"
```

**Comment by chris-sanders** [comment]
@banjoh this chat has been removed, can you clarify what the bug is in the library chart specifically if this still aplies?

**Comment by banjoh** [comment]
@chris-sanders the bug is in the library, I believe [here](https://github.com/replicatedhq/helm-charts/blob/3643c2dac5c225afa3e58bca0a67b228b622cc7b/charts/replicated-library/values.yaml#L41)

I cloned ran the [moved wg-easy chart](https://github.com/chris-sanders/helm-charts/tree/master/charts/wg-easy) and recreated the same bug. There are the steps

- Clone the repo or download the [moved wg-easy chart](https://github.com/chris-sanders/helm-charts/tree/master/charts/wg-easy)
- Run the commands below
```sh
helm package --dependency-update .
```
- Observe the generated support bundle secret
```
[evans] $ helm template wg-easy-0.0.1.tgz | head -n 30
---
# Source: wg-easy/templates/replicated-library.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-wg-easy-support-bundle-replicated
  labels:
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |-
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: release-name-wg-easy-support-bundle-replicated
    spec:
      collectors:
        - clusterInfo: {}
        - clusterResources: {}
        - ceph: {}
        - longhorn: {}
        - exec:
            selector:
              name: weave-net
              - /home/weave/weave
            collectorName: weave-status
            name: kots/kurl/weave
            containerName: weave
            namespace: kube-system
            timeout: 10s
            args:
```

The support bundle spec is enabled/disabled using the values below which can be seen [here](https://github.com/chris-sanders/helm-charts/blob/d7fd18eb3283e3e9b0885a10d8fe76cde8be2efa/charts/wg-easy/values.yaml#L94)
```yaml
# Troubleshoot
troubleshoot:
  support-bundles:
    # Replicated supplied default support bundle spec
    replicated:
      # -- Enables or disables the Replicated default support bundle
      enabled: true
```

**Comment by chris-sanders** [comment]
Since this chart is no longer part of this repository I propose demonstrating the issue with the new testing functionality so that it's both clear how to cause it, and we can use that test to develop TDD solution as well.

**Comment by banjoh** [comment]
- Create a test values file [here](https://github.com/replicatedhq/helm-charts/tree/main/test/test-values) and name it `default_support_bundles_enabled.yaml`.
- Add the contents below
```yaml
# Troubleshoot
troubleshoot:
  support-bundles:
    # Replicated supplied default support bundle spec
    replicated:
      # -- Enables or disables the Replicated default support bundle
      enabled: true
```
- Run the commands below
```sh
helm dependency update test-chart/
helm template test-chart/ --values test-values/default_support_bundles_enabled.yaml | head -n 30
```
- Expect to get the output below
```yaml
---
# Source: test/templates/replicated-library.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-test-support-bundle-replicated
  labels:
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |-
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: release-name-test-support-bundle-replicated
    spec:
      collectors:
        - clusterInfo: {}
        - clusterResources: {}
        - ceph: {}
        - longhorn: {}
        - exec:
            selector:
              name: weave-net
              - /home/weave/weave
            collectorName: weave-status
            name: kots/kurl/weave
            containerName: weave
            namespace: kube-system
            timeout: 10s
            args:
              - --local
              - status
        - exec:
            selector:
              name: weave-net
              - /home/weave/weave
            collectorName: weave-report
            name: kots/kurl/weave
            containerName: weave
            namespace: kube-system
            timeout: 10s
            args:
              - --local
              - report
        - logs:
            selector:
              name: weave-net
            collectorName: weave-net
            name: kots/kurl/weave
            namespace: kube-system
        - logs:
            selector:
              app: flannel
            collectorName: kube-flannel
            name: kots/kurl/flannel
            namespace: kube-flannel
        - collectd:
            hostPath: /var/lib/collectd/rrd
            image: alpine
            collectorName: collectd
            timeout: 5m
            imagePullPolicy: IfNotPresent
```

**Not the following**
- The `exec` collectors are all wrong. The `name` & `selector` fields in each others places, there is a duplicate fields and indentation is not correct. I expect the spec to look like so
```yaml
        - exec:
            name: kots/kurl/weave
            selector:
              - /home/weave/weave
            containerName: weave
            namespace: kube-system
            timeout: 10s
            args:
              - --local
              - status
```
- Pod logs collectors have selectors as key-value instead of lists. I expect to see this.
```yaml
    - logs:
        selector:
          - app=api
```
