### ISSUE TITLE
Unable to use secrets or configMaps for container env variables.

### ISSUE THREAD

**Issue by drohnow** [replicatedhq/helm-charts#99]
current version of chart will only allow the following configuration to be utilized for container env variables:

"variable": "value"

sample snippet of container configuration:

```
        env:
          WORDPRESS_DB_HOST: my-wp-dagr-mysql
          WORDPRESS_DB_NAME: wpdb
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: Trek1515
          WORDPRESS_DEBUG: "1"   
       
```

However, when I attempt to utilize a secret or a configMap for specifying an environment value with this configuration:

<img width="774" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/9b2d7220-0a76-4389-952c-de136a806780">

It will render:

<img width="325" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/64b9e334-fc72-4fb4-aeb0-a58313d91a23">

However, it will not validate and create a deployment object:
receive this error:

```
Error: INSTALLATION FAILED: 1 error occurred:
	* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal object into Go struct field EnvVar.spec.template.spec.containers.env.value of type string

```

**Comment by diamonwiggins** [comment]
@drohnow yup, the only way today to use a configmap or secret for env vars is to use `envFrom`. We still need to add support to `env` for the format you're mentioning here as well as:

```yaml
env:
  - name: var
     value: value
```

**Comment by drohnow** [comment]
Right on! Please check my PR that I just created to see if that will work for us.

**Comment by diamonwiggins** [comment]
https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/templates/lib/controller/_env_vars.tpl isn't an exact example of where we'll land but likely will be a helpful example in demonstrating how we can support multiple formats here. the k8s at home chart supports:

```
# A) TZ: UTC
# B) PASSWD: '{{ .Release.Name }}'
# C) PASSWD:
#      configMapKeyRef:
#        name: config-map-name
#        key: key-name
# D) PASSWD:
#      valueFrom:
#        secretKeyRef:
#          name: secret-name
#          key: key-name
#      ...
# E) - name: TZ
#      value: UTC
# F) - name: TZ
#      value: '{{ .Release.Name }}'
```

**Comment by drohnow** [comment]
@diamonwiggins I gave it a try what I think I am struggling with is understanding the right context that is needed for the tpl function in our Lib Chart.

**Comment by drohnow** [comment]
Use case 1: 
   
```
env:
      foo: bar
```
   values.yaml snippet:

```

apps:
  mysql:
    enabled: true
    type: statefulset
    serviceName: mysql-wp
    replicas: 1
    imagePullSecrets: []
    containers:
      mysql:
        image:
          repository: mysql
          tag: latest
          pullPolicy:
        command: []
        args: []
        env:
          MYSQL_ROOT_PASSWORD: password # will render and deployment object will be created.

```


test one: helm template wp-dagr/

<img width="410" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/b7a4f638-19c7-4d36-9df0-f7f74d5827a2">
results: template renders correctly


test two: create deployment object (helm install t wp-dagr/)
<img width="698" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/a85c9fc5-a48b-48b1-8c6a-9642d47af1d7">

kubectl get pod -o yaml t-wp-dagr-mysql-0 snippet:
<img width="388" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/e997a42a-840e-4851-9844-cfa8244cfab9">

note: Mysql pod will only come up if the "MYSQL_ROOT_PASSWORD" environment variable is set.

Use case 2: 
   
```
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password

```
   values.yaml snippet:

```
apps:
  mysql:
    enabled: true
    type: statefulset
    serviceName: mysql-wp
    replicas: 1
    imagePullSecrets: []
    containers:
      mysql:
        image:
          repository: mysql
          tag: latest
          pullPolicy:
        command: []
        args: []
        env:
          - name: MYSQL_ROOT_PASSWORD  # will render and deployment object will be created.
            value: password

```
test one: helm template wp-dagr/

<img width="410" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/b7a4f638-19c7-4d36-9df0-f7f74d5827a2">
results: template renders correctly

test two: create deployment object (helm install t wp-dagr/)
<img width="713" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/dab0e3cd-49b2-4a4a-b6f3-47b5c96bd24c">

kubectl get pod -o yaml t-wp-dagr-mysql-0 snippet:
<img width="238" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/caf22281-1e62-4721-81ca-b588581c5881">

note: Mysql pod will only come up if the "MYSQL_ROOT_PASSWORD" environment variable is set.

Use case 3: 
   
```
        env:
        - name: MYSQL_ROOT_PASSWORD  # Renders & installs statefulset with said environment variable.
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: MYSQL_ROOT_PASSWORD


```
   values.yaml snippet:

```
        - name: MYSQL_ROOT_PASSWORD  # will render and deployment object will be created.
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: MYSQL_ROOT_PASSWORD

```
test one: helm template wp-dagr/
<img width="311" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/c729d43b-12ec-440b-bc83-acbfdece2acd">
results: template renders correctly

test two: create deployment object (helm install t wp-dagr/)

<img width="697" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/1f4ffc36-7bd2-4d26-bc22-40c812cdaa28">


kubectl get pod -o yaml t-wp-dagr-mysql-0 snippet:

<img width="299" alt="image" src="https://github.com/replicatedhq/helm-charts/assets/30049377/249d4e84-006d-4972-8c63-915df8f503f8">


note: Mysql pod will only come up if the "MYSQL_ROOT_PASSWORD" environment variable is set.
